---
kind: Namespace
apiVersion: v1
metadata:
  name: edgar-<<<container.environment>>>

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: edgar-<<<container.environment>>>
  namespace: edgar-<<<container.environment>>>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgar-<<<container.environment>>>
  template:
    metadata:
      labels:
        app: edgar-<<<container.environment>>>
    spec:
      containers:
        - name: edgar-<<<container.environment>>>
          image: <<<container.image>>>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "0.5"
              memory: "2Gi"
---
kind: Service
apiVersion: v1
metadata:
  name: edgar-<<<container.environment>>>
  namespace: edgar-<<<container.environment>>>
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate. ---- arn:aws:acm:eu-west-1:411447780843:certificate/a963ca1c-30a1-431a-b1d4-35e1f4d7744e
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <<<container.certificate>>>
    # Only run SSL on the port named "https" below.
    external-dns.alpha.kubernetes.io/hostname: <<<container.dns>>>
spec:
  selector:
    app: edgar-<<<container.environment>>>
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
