---
kind: Namespace
apiVersion: v1
metadata:
  name: hugo-<<<container.environment>>>

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hugo-<<<container.environment>>>
  namespace: hugo-<<<container.environment>>>
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hugo-<<<container.environment>>>
  template:
    metadata:
      labels:
        app: hugo-<<<container.environment>>>
    spec:
      containers:
        - name: hugo-<<<container.environment>>>
          image: <<<container.image>>>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "0.5"
              memory: "2Gi"
---
kind: Service
apiVersion: v1
metadata:
  name: hugo-<<<container.environment>>>
  namespace: hugo-<<<container.environment>>>
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <<<container.certificate>>>
    # Only run SSL on the port named "https" below.
    external-dns.alpha.kubernetes.io/hostname: <<<container.dns>>>
spec:
  selector:
    app: hugo-<<<container.environment>>>
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
